### ISSUE TITLE
Document that Func_godot can be used with other languages

### ISSUE THREAD

**Issue by RisingThumb** [func-godot/func_godot_docs#2]
From this PR: https://github.com/func-godot/func_godot_plugin/pull/11

This is mainly to help people who use C# be able to use the plugin, since it's been asked a few times in the Discord(and the related PR follows from it)

**Comment by RhapsodyInGeek** [comment]
Honestly, out of scope for the purpose of the docs. There's nothing to suggest that other languages like C#, C++, Rust, can't be used, and anyone using another language with Godot in general should know how to expose methods to Godot callbacks.

The docs should be focused on how func_godot works and how to use it. We needn't become documentation for how to use Godot as well.

**Comment by RisingThumb** [comment]
> There's nothing to suggest that other languages like C#, C++, Rust, can't be used

There's nothing to suggest it can be either which is why people have asked a few times in the discord. If it becomes a FAQ, may be worth revisiting
